[workspace]
name = "ue-ros-bridge"
channels = ["https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[activation.env]
RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"

[tasks]
setup = "sh setup.sh"
talker = "ros2 run demo_nodes_cpp talker"
listener = "ros2 run demo_nodes_cpp listener"

[dependencies]
cmake = ">=4.4.3,<5"
git = ">=2.55.0,<3"
ros-jazzy-demo-nodes-cpp = ">=0.33.11,<0.34"
ros-jazzy-ros2run = ">=0.32.11,<0.33"
ros-jazzy-ros2topic = ">=0.32.11,<0.33"
ros-jazzy-rmw-cyclonedds-cpp = ">=2.2.3,<3"
